<Tela1>:
    Label:
        text: "isso ta na tela1"
        color: (0, 1, 0, 1)
    Button:
        text: "tela1"
        #função que esta na classe principal
        on_press: root.on_press_executar_tela1()
        color: (0, 1, 0, 1)
<Tela2>:
    Label:
        color: (1, 0, 0, 1)
        text: "isso ta na tela2"
    Button:
        text: "tela2"
        on_press: root.on_press_executar_tela2()
