# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/screen/main_window/view/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        main_window.setMinimumSize(QtCore.QSize(800, 600))
        main_window.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.login_form_frame = QtWidgets.QFrame(self.centralwidget)
        self.login_form_frame.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.login_form_frame.setMinimumSize(QtCore.QSize(800, 600))
        self.login_form_frame.setMaximumSize(QtCore.QSize(800, 600))
        self.login_form_frame.setStyleSheet("padding: 0 20px;")
        self.login_form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_form_frame.setObjectName("login_form_frame")
        self.login_message_label = QtWidgets.QLabel(self.login_form_frame)
        self.login_message_label.setGeometry(QtCore.QRect(20, 410, 761, 181))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.login_message_label.setFont(font)
        self.login_message_label.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.login_message_label.setText("")
        self.login_message_label.setObjectName("login_message_label")
        self.clock = QtWidgets.QLabel(self.login_form_frame)
        self.clock.setGeometry(QtCore.QRect(240, 0, 221, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.clock.setFont(font)
        self.clock.setObjectName("clock")
        self.formLayoutWidget = QtWidgets.QWidget(self.login_form_frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 100, 761, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.form = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.form.setContentsMargins(0, 0, 0, 0)
        self.form.setObjectName("form")
        self.password_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_input = QtWidgets.QTextEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("padding:\"10px\";\n"
"border: none;")
        self.password_input.setObjectName("password_input")
        self.form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.password_input)
        self.login_label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.login_label)
        self.login_input = QtWidgets.QTextEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.login_input.setFont(font)
        self.login_input.setStyleSheet("padding:\"10px\";\n"
"border: none;")
        self.login_input.setObjectName("login_input")
        self.form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.login_input)
        self.login_submit_button = QtWidgets.QPushButton(self.login_form_frame)
        self.login_submit_button.setGeometry(QtCore.QRect(530, 330, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_submit_button.setFont(font)
        self.login_submit_button.setObjectName("login_submit_button")
        main_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Sistema De Debitos"))
        self.clock.setText(_translate("main_window", "00:00:00"))
        self.password_label.setText(_translate("main_window", "SENHA"))
        self.password_input.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.login_label.setText(_translate("main_window", "LOGIN"))
        self.login_input.setHtml(_translate("main_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:28pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.login_submit_button.setText(_translate("main_window", "Entrar"))
