<Tela1>:
    #existem varios tipos de orientação para o empilhamento
    orientation: "tb-lr"
    Button:
        text: "bt1"
        size_hint: .1, .33

    Button:
        text: "bt1"
        size_hint: .1, .33

    Button:
        text: "bt1"
        size_hint: .1, .33

    Button:
        text: "bt1"
        size_hint: .1, .33

    Button:
        text: "bt1"
        size_hint: .1, .33

    Button:
        text: "bt1"
        size_hint: .1, .33
