<Tela1>:
    #existem varios tipos de orientação para o empilhamento
    cols: 5#colunas
    rows: 4#linhas
    #col_default_height: 100
    #col_force_default: True
    row_default_height: 100
    row_force_default: True

    Button:
        text: "bt1"

    Button:
        text: "bt1"

    Button:
        text: "bt1"

    Button:
        text: "bt1"

    Button:
        text: "bt1"

    Button:
        text: "bt1"
        #aumenta o tamanho dessa coulona
        size_hint: .5, .1
