<Tela>:
    orientation: 'tb-lr'
    StackLayout:
        padding: .5
        id: botoes
        orientation: 'tb-lr'
        Button:
            text: "bt"
            size_hint: None, None
            size: 100, 50
    FloatLayout:
        Button:
            text: "Adicionar"
            size_hint: None, None
            size: 150, 50
            pos_hint: {"x": 0, "y": 0}
            on_press: root.adiciona_botao()
