from random import shuffle
alunos = ['ADSON DA SILVA NOVAES', 'ALEXANDRE ANTONIO SILVA SANTOS', 'ANA CAROLINA CANDIDO DE MELO', 'BRUNA EDUARDA ALVES LEAL DE SOUZA', 'BRUNO ARTHSSON SILVA', 'CARLA JAQUELINE NOGUEIRA DE SOUSA', 'CRISTÓVÃO CADIZ DE LIMA', 'DEBORA LUANA DE JESUS SILVA', 'EDUARDO GOMES FERREIRA SOUZA', 'EMANUELA PEREIRA DOS SANTOS', 'FLAVIO CORDEIRO ROCHA JUNIOR', 'HITALO FILLIPY DE LIMA MAGALHAES', 'INACIO FERRAZ PINTO JUNIOR', 'ISRAEL PEREIRA MENDES DA SILVA SOBRINHO', 'IURY SOUZA BARROS', 'JOÃO PAULO ALVES BERNARDO DE LIMA', 'JONAS DE JESUS NUNES', 'JORGE LUIZ OTAVIO DA SILVA BRITO', 'JOSE RAIMUNDO DA SILVA FILHO', 'JULIO CESAR DA COSTA LOPES', 'LEDSON JOSÉ DOS SANTOS SOUZA', 'LUCAS GOIANA NOVAES RODRIGUES', 'LUCAS PEREIRA DE SOUZA', 'LUIZ ANTONIO PEREIRA CAMPOS', 'MATHEUS BARBOSA SOUZA', 'MATHEUS HONORIO QUEIROZ DE AZEVEDO', 'PEDRO VINICIUS ALCANTARA OLIVEIRA', 'RAUL VICTOR DE SOUZA', 'ROMARIO ELIAS DA SILVA SANTOS', 'SAMARA KELLY PEREIRA SIQUEIRA', 'THIAGO JOSÉ SILVA DOS SANTOS', 'THIAGO LOURIVAL DE SOUZA ALMEIDA', 'WILBER JALLISON EUGENIO LOPES', 'PATRICIA MENEZES', 'JOÃO RAPHAEL']

shuffle(alunos)

grupo = 1
total = 0
a = 0
while a < len(alunos):
    if total == 0:
        print('Grupo: {}'.format(grupo))
    elif total == 6:
        total = 0
        grupo += 1
        continue

    print('\t{}'.format(alunos[a]))
    a += 1
    total += 1